apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-reader
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services"]
  verbs: ["get", "watch", "list"]
  
# Habilita acesso no deployment

# - apiGroups: ["apps"]
#   resources: ["deployments"]
#   verbs: ["get", "watch", "list"]
  
